# Generated by Django 5.2.17 on 2026-09-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citation', '0036_alter_suggestedmerge_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='year_published',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
    ]
